version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 15672:15672
      - 5672:5672
    expose:
      - 5672
    networks:
      - barbershopnet24

  barbershop-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
      - 1433
    networks:
      - barbershopnet24

  email-notification-service:
    restart: unless-stopped
    build:
      context: .
      dockerfile: EmailNotificationService\Dockerfile
    environment:
      - RabbitMQ_HostName=rabbitmq
      - RabbitMQ_UserName=guest
      - RabbitMQ_Password=guest
      - Outlook_Mail=barbershop_rs2@outlook.com
      - Outlook_Password=Barbershop!
    depends_on:
      - rabbitmq
      - barbershop-sql
      - barbershop-api
    networks:
      - barbershopnet24
    ports:
      - 7101:80

  barbershop-api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: API\Dockerfile
    environment:
      - ConnectionStrings:DefaultConnection=Server=barbershop-sql,1433;Database=180044;User=sa;Password=QWElkj132!;ConnectRetryCount=0;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ_HostName=rabbitmq
      - RabbitMQ_UserName=guest
      - RabbitMQ_Password=guest
    ports:
      - 5001:80
    networks:
      - barbershopnet24
    links:
      - barbershop-sql
    depends_on:
      - barbershop-sql
      - rabbitmq

networks:
  barbershopnet24:
    driver: bridge
